README.md, js/urlSettingsForm.js, shoreditch.php
Adds an easy gui button in **Administer -> System Settings -> Resource URLs** for the shoreditch custom css file.
=> Add user-friendly way to add custom css

CONTRIBUTING.md
We deleted the `develop` branch, so we need to reference `master` in the documentation now
=> Use master as the target branch of PRs in documentation

scss/civicrm/contact/pages/_reports.scss
This PR styles minor glitches in report pages
**Before**
**After**
- Stylelint tested
- BackstopJS tested
=> NDI-41: Style report pages

package-lock.json
Unfortunately the fix in #228 didn't work, due to the `package-lock.json` file not being updated correctly, thus not making the warning disappear
The problem appears to be on whether `hoek` is listed as a 1st-level property in the lock file: if it is, then GitHub will display the warning. The instructions mentioned in the previous PR are meant to fix this problem, basically resulting in a diff containing this change:
For some reason the lock file in the previous PR, although changed, didn't contain that particular changes, and thus the problem was not fixed.
Running the instructions again
```bash
npm install hoek && npm uninstall hoek && npm update && npm i 
```
resulted in the lock file contained in this PR, which should fix the issue.
Sanity checks that I've run before submitting the …
=> PCHR-3635: Fix for #228

js/contact-summary.js
The new version of contact-summary.js written as part of #285 was assuming that there is always a profile picture in the contact summary page, which is not really the case. As a result when the picture was missing, it would throw an error
A simple guard prevents the issue
```js
function manipulateProfilePicture () {
var picWrapper = document.querySelector('#crm-contact-thumbnail');
if (!picWrapper) {
return;
}
usePictureAsBackground();
moveUserPictureNextToContactTitle();
}
```
The script has also been refactored a little to remove code duplication
=> SHOR-71: Improve profile pic manipulation logic

CODING.md
Simply adding a reference to the location of the git hooks in CODING.md, and how to manually install the post-checkout hook
=> SHOR-93: Add location of hooks in CODING.md and manual install command

CODING.md, package.json
The automatic hiding of  .css files (see https://github.com/civicrm/org.civicrm.shoreditch/pull/320, "Automatic ignore of css files on postinstall") proved to be a lit bit too disorienting, so I'm disabling it and just giving it as an option in CODING.md
=> SHOR-93: Remove automatic skip-worktree

scss/civicrm/contact/pages/_view-contact.scss
This PR fixes the custom data data displayed on the contact details. The table is not expanded properly due to an outdated CSS rule. Also, the alignment of the delete action button has been fixed.
* Create a custom field group for contacts.
* Add new fields to that custom field group.
* Open any contact and view their details.
* Click on the tab with the name of the new custom field group.
The problem is that the following rule:
```scss
table.crm-info-panel td.html-adjust {
width: 100%;
}
```
Overrides the natural width of the column. The label column is `150px` and the value column would take up the rest, but if `width: 100%` is specified the column would try to take as much space as possible and break the label column's width.
This rule was first introduced in the following PR for an …
=> SHOR-105: Fix Contact Custom Data Tab

scss/civicrm/contact/_tooltip.scss
This PR displays all contact actions that were previously hidden for CiviHR.
`Add Case`, `Add Relationship`, `Add Note`, and `Tag Contact` are missing.
The issue happened when merging missing CiviHR fixes into Shoreditch in this PR:
https://github.com/civicrm/org.civicrm.shoreditch/pull/1
The changes were necessary, but the one removing the contact actions was too specific for CiviHR and was not needed by Shoreditch. These particular changes were removed:
```scss
.crm-action-new-case,
.crm-action-new-relationship,
.crm-action-new-note,
.crm-action-tag-contact {
display: none;
}
```
Backstop tests for the contact page ran successfully.
=> SHOR-108: Show all contact actions

scss/civicrm/contact/pages/_events.scss
This PR fixes the following issues with custom fields for the contact's events tab:
* margins for the accordion title inside when creating a new event participation for the contact.
* The styles of the custom fields when viewing the participation.
Since the events form is a custom form with custom markup and css rules compared to those of other forms, the negative margin added here:
https://github.com/reneolivo/org.civicrm.shoreditch/blob/988ec9756af56a7cfa9940853ea2bc48f6cdace0/scss/civicrm/contact/pages/_events.scss#L281
Is removed for accordion wrappers:
```scss
.crm-accordion-wrapper {
margin-left: 0;
margin-right: 0;
}
```
The PR that first introduced the changes for the participation view modal is this one:
https://github.com/compucorp/civihr/pull/1639
The form has changed since …
=> SHOR-106: Fix margins for contact's participation custom fields

package-lock.json, package.json
Updating npm dependencies.
There are two major version bumps:
```diff
- "stylelint": "^8.4.0",
+ "stylelint": "^9.10.1",
```
```diff
-  "stylelint-order": "^0.8.1",
+ "stylelint-order": "^2.0.0",
```
The changelogs ([#1](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md), [#2](https://github.com/hudochenkov/stylelint-order/blob/master/CHANGELOG.md)) show that the new major versions have been introduced just to mark the support drop of dependencies' old versions (Node.js 4.x , stylelint@8). Given that we are not using those versions, it's safe to upgrade
=> PCHR-4494: Update dependencies

scss/civicrm/common/_buttons.scss
This PR fixes the issue with actions icons in CiviCRM.
The problem is at *scss/civicrm/common/_buttons.scss*:
```
...
.crm-hover-button,
... {
@extend %btn;
}
```
The `%btn` changes the font to `OpenSans` while it should be kept as `FontAwesome` but only for icons, so:
```
.crm-hover-button.crm-i {
font-family: $font-family-fontawesome !important;
// !important is needed because %btn contains !important too
}
```
is a safe way to keep the font correct and do not produce regressions.
This is an extremely minor change, so only **manual** tests were performed to save time.
=> BASW-379: Fix CiviCRM action item icons

scss/civicrm/_mixins.scss, scss/civicrm/_variables.scss, scss/civicrm/common/_base.scss, scss/civicrm/common/_forms.scss, scss/civicrm/common/_tables.scss, scss/civicrm/contact/_contact.scss, scss/civicrm/contact/pages/_memberships.scss, scss/civicrm/contact/pages/_rules.scss, scss/civicrm/mixins/_block-form.scss, scss/civicrm/mixins/_table-selector.scss
This PR styles CiviRules extension pages.
_Please note, this page was just used as an example_
We need this mixin to fix the layout of block forms.
```css
@mixin block-form() {
// otherwise, fields are attached to the borders, which is ugly
padding-bottom: $crm-standard-gap !important;
padding-top: $crm-standard-gap !important;
// otherwise, fields are attached to the borders, which is ugly
.label,
.content {
padding-left: $crm-standard-gap;
.content {
padding-right: $crm-standard-gap;
// no last margin needed
.crm-section:last-of-type {
margin-bottom: 0;
// used in each row
.clear {
// This value is taken from the vanilla CiviCRM
margin-bottom: 1em;
&:last-of-type {
margin-bottom: 0;
// this is for other type of tables
.form-layout {
margin-top: $crm-standard-gap;
tr td:first-of-type { …
```
=> SHOR-122: Style CiviRules extension

scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_memberships.scss, scss/civicrm/mixins/_civicrm-table.scss
This PR fixes the issue with shadows on the Contribution tab.
Notice overlayed shadows:
Notice the extra thick shadow on the table header:
We add a mixin that supports this layout: H3 + Table in a Wrapper. We remove shadows from tables and headers and apply a solid shadow on the wrapper.
```css
@mixin civicrm-table-with-header() {
box-shadow: $box-shadow;
h3,
table {
box-shadow: none !important;
}
.columnheader {
border: 0 !important;
border-bottom: 1px solid $crm-grayblue-dark !important;
}
}
```
It was considered to:
1) find a universal style, but unfortunately there is no distinctive and reliable way to apply needed styles to only needed table due to inconsistency of markup.
2) change the markup - this is too complicated and will require changing markup in several extensions and also …
=> BASW-376: Fix shadows of tables on Contribution tab

base/js/affix.js, base/js/alert.js, base/js/button.js, base/js/carousel.js, base/js/collapse.js, base/js/dropdown.js, base/js/modal.js, base/js/popover.js, base/js/scrollspy.js, base/js/tab.js, base/js/tooltip.js, base/js/transition.js, base/scss/vendor/bootstrap/_modals.scss, base/scss/vendor/bootstrap/_theme.scss, package-lock.json, package.json
Bootstrap has released [v3.4.1](https://github.com/twbs/bootstrap/releases/tag/v3.4.1), same for [bootstrap-sass](https://github.com/twbs/bootstrap-sass/releases/tag/v3.4.1), so we need to upgrade the dependency in Shoreditch
There are no changes to the stylesheets, only security-related JS changes
=> SHOR-131: Upgrade to bootstrap-sass@3.4.1

scss/civicrm/_variables.scss, scss/civicrm/contact/pages/_memberships.scss
This PR simply adds a padding to the header on the New Membership screen.
```
#recordContribution {
margin-top: $crm-standard-gap;
```
Please note `$crm-standard-gap: 20px;` variable exists in BASW-377, so we duplicate it in this PR to reuse.
The form was tested manually.
=> BASW-375: Adhoc the legend header for Memberships

scss/civicrm/contact/_tabs.scss
This styles the counters in the vertical tabs follow the bootstrap convention of [badges](https://getbootstrap.com/docs/3.3/components/#badges).
- Empty count will disappear
- Count of 0 will be grey
- Count > 0 will be primary color
=> Style contact tab counts to look like badges

scss/civicrm/common/_forms.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_memberships.scss
This PR fixes issue with form inputs that have input errors. Actually, this PR fixes a blocker because it becomes impossible to type anything in input fields once an error is spawned because inputs' text color becomes white on white background and thus invisible.
1) Input height is changed
2) Text inside inputs is white and thus invisible
You can see the input text, inputs are rendered consistently and error labels look good as well.
None of the styles above are suitable for inputs, so we are excluding inputs from this styling. We also add two styles which are used in extensions to globalise the styling.
```css
.crm-inline-error {
/* &:not(.crm-error-label) { */
&:not(.crm-error-label):not(input):not(textarea):not(select) {
background: $brand-danger; 
border-radius: 3px; /* Moving this …
```
=> BASW-380: Fix styles of inputs with errors

TESTING.md, scss/civicrm/_variables.scss, scss/civicrm/administer/settings/_extensions.scss, scss/civicrm/common/_alerts.scss, scss/civicrm/common/_base.scss, scss/civicrm/common/_modals.scss, scss/civicrm/contact/_detail.scss, scss/civicrm/contact/pages/_batch.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_events.scss, scss/civicrm/contact/pages/_memberships.scss, scss/civicrm/contact/pages/_new-activity.scss, scss/civicrm/contact/pages/_new-individual.scss, scss/civicrm/contact/pages/_relationships.scss
This PR fixes appearance of contents inside modals. In a nutshell, it removes "per-page" code applied to "fix" the issues with the content, then applies global fixes, then applies _some_ "per-page" code where fixing globally is not viable.
The Recurring Contributions "view" modal looks totally broken:
This PR applies new global styling for modals and their contents, thus a lot of modals now look slightly different, in a good way. This GIF is a very long one but it shows all modals and proves that global styling works:
At first, we created a new global style that applies to all modals and removed "per-page" styles related to modals, that fixed the initial screen that you see in Before/After sections and also other modals:
*scss/civicrm/common/_modals.scss*
```css
.ui-dialog-content {
table …
```
=> BASW-377: Fix styles in new contribution modal

package-lock.json, package.json
The [extend](https://www.npmjs.com/package/extend) module needed to be upgraded to the `3.0.2` version for security reasons
=> SHOR-134: Patch extend module

scss/civicrm/_variables.scss, scss/civicrm/common/_modals.scss, scss/civicrm/contact/pages/_events.scss, scss/civicrm/contact/pages/_new-activity.scss
This PR fixes regressions produced by https://github.com/civicrm/org.civicrm.shoreditch/pull/363.
One solution has fixed the gaps in the modals after `.crm-block` but this cause regressions in other places, once reverted, the gap appeared again (after 100$ row):
`[colspan='2']` is the only way to detect accordions. However, this selector is also used inside accordions, because it is pretty general, so we need to discard the styling to the original state.
```css
.ui-dialog-content {
table {
&.form-layout,
&.form-layout-compressed {
> tbody > tr > td[colspan='2'] {
padding: 0;
// discarding nested
.form-layout,
.form-layout-compressed {
td[colspan='2'] {
padding: $crm-table-form-cell-padding;
```
Note: everything listed here was added in …
=> SHOR-133: Fix styles for tables, forms and modals

scss/civicrm/main-menu/_main-menu.scss
Closes #341 
This PR is a subset of #359, I've kept only the one change that was strictly about the search results being always visible
=> SHOR-135: Fix position of quicksearch results

README.md, scss/civicrm/_variables.scss, scss/civicrm/contact/pages/_pivot-report.scss, scss/civicrm/contact/pages/_rules.scss, scss/civicrm/custom-civicrm.scss, scss/civicrm/mailing/_mailing.scss, scss/civicrm/mailing/pages/_mailing-all.scss, scss/civicrm/mailing/pages/_mailing-report.scss, scss/civicrm/mailing/pages/_mailing-search.scss
This PR styles the following screens in CiviCRM:
- Mailing Browse / Search - `/civicrm/mailing/browse/unscheduled?reset=1&scheduled=false`
- Mailing Reports - `/civicrm/mailing/report?mid=5&reset=1`
We did not amend any core markup to avoid unexpected changes in CiviCRM UI without Shoreditch. Instead, we applied **isolated** per-page CSS styles. The styles are trivial in most places but there is one specific to note explicitly:
```
#{civi-page('mailing-report')} {
fieldset {
legend {
... 
// Otherwise it will actually be "detached" from the fieldset
float: left;
```
The reason is that we can either same selectors as Civi or `!important`. In that particular case, when we are styling a page, `!important` has more sense because the code looks cleaner and we will not need to override these …
=> SHOR-143: Style Mailing screens

.gitignore, scss/civicrm/_variables.scss, scss/civicrm/administer/_administer.scss, scss/civicrm/administer/report/_report.scss, scss/civicrm/cases/_cases.scss, scss/civicrm/cases/_search.scss, scss/civicrm/common/_block-shadows.scss, scss/civicrm/common/_buttons.scss, scss/civicrm/common/_common.scss, scss/civicrm/common/_forms.scss, scss/civicrm/common/_modals.scss, scss/civicrm/contact/pages/_activities.scss, scss/civicrm/contact/pages/_batch.scss, scss/civicrm/contact/pages/_contact-dedupefind.scss, scss/civicrm/contact/pages/_find-and-merge-duplicate.scss, scss/civicrm/contact/pages/_pivot-report.scss, scss/civicrm/contact/pages/_rules.scss, scss/civicrm/mailing/pages/_mailing-report.scss, scss/civicrm/mailing/pages/_mailing-search.scss, scss/jquery/overrides/_select2.scss
This PR fixes miscellaneous issues with CiviCRM / Shoreditch styling. Please see the "Changes" section for more information.
| Report Register header shadows and action buttons | ![image](https://user-images.githubusercontent.com/3973243/62858287-ca60ea00-bcf1-11e9-8132-4c4d93da0704.png) | ![image](https://user-images.githubusercontent.com/3973243/62868923-a233b400-bd0e-11e9-9e69-51ea72eef810.png) | Yes, shadows |
| Fix paddings, labels positioning and button icons in Case Search | ![AwesomeScreenshot-localhost--civicrm-case-search-2019-08-15_3_22](https://user-images.githubusercontent.com/3973243/63101217-79aaf480-bf70-11e9-8c53-57ae1eed4382.png) | …
=> SHOR-141: Fix misc issues with CiviCRM and Shoreditch UI

scss/civicrm/common/_forms.scss, scss/civicrm/contact/pages/_events.scss
This PR fixes miscellaneous issues with CiviCRM / Shoreditch styling. Please see the "Changes" section for more information.
| Event Fees table misalignment | ![image](https://user-images.githubusercontent.com/3973243/63158777-ed510e00-c011-11e9-9719-95708b8e0305.png) | ![image](https://user-images.githubusercontent.com/3973243/63158858-0eb1fa00-c012-11e9-901e-f972ad84d0f8.png) | No |
| Manage Events shadows | ![AwesomeScreenshot-localhost-civicrm-event-manage-2019-08-16_10_34](https://user-images.githubusercontent.com/3973243/63158562-68fe8b00-c011-11e9-9f3b-fd6e19292f51.png) | ![AwesomeScreenshot-localhost-civicrm-event-manage-2019-08-16_10_26](https://user-images.githubuser …
=> SHOR-149: Fix misc issues with CiviCRM and Shoreditch UI

scss/civicrm/common/_block-shadows.scss, scss/civicrm/contact/pages/_rules.scss
This PR fixes multiple visual issues in CiviRules and GDPR extensions. Please see the Changes sections for more info.
| CiviRules - missing padding in one of forms | ![image](https://user-images.githubusercontent.com/3973243/63260719-99486280-c279-11e9-9e83-6ec81cbbbbb2.png) | ![image](https://user-images.githubusercontent.com/3973243/63259518-82544100-c276-11e9-9e94-94b5a31fa2b0.png) | No, isolated to the specific CiviRules form |
| GDPR - Any contact > GDPR Tab - Unneeded shadow  | ![Alexia Adams _ civi16newby (3)](https://user-images.githubusercontent.com/3973243/63260517-12938580-c279-11e9-83ed-993094b84acf.png) | ![Alexia Adams _ civi16newby …
=> SHOR-139: CiviRules and GDPR fixes

scss/civicrm/_mixins.scss, scss/civicrm/administer/contribute/_contribute.scss, scss/civicrm/common/_block-shadows.scss, scss/civicrm/common/_titles.scss, scss/civicrm/contact/pages/_events.scss, scss/civicrm/contact/pages/_memberships.scss, scss/civicrm/mixins/_alpha-filter.scss
This PR fixes issues with shadows on some pages where the markup is not standard so global fixes from https://github.com/civicrm/org.civicrm.shoreditch/pull/402 cannot be applied. Shadows are fixed on the following pages:
- CiviMember
- CiviEvent
- Manage Contribution Pages
As a side effect, the following pages also have been automatically fixed:
- Contacts Full-text Search
Please see the Changes section for more info.
| Manage Contribution Pages - Shadows | ![Manage Contribution Pages _ civi16newby (2)](https://user-images.githubusercontent.com/3973243/63275936-521e9980-c29a-11e9-99f6-6cefe88e037a.png) | ![Manage Contribution Pages _ civi16newby …
=> SHOR-152: Fix shadows on unusual <h3> + <div> pairs

scss/civicrm/common/_block-shadows.scss, scss/civicrm/common/_forms.scss, scss/civicrm/common/_help.scss, scss/civicrm/contact/_detail.scss, scss/civicrm/contact/_header.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_manage-groups.scss, scss/civicrm/contact/pages/_memberships.scss
This PR fixes miscellaneous issues with Shoreditch. Please see the **Changes** section below for more info.
| CiviContribute: shadows and gaps | ![CiviContribute _ civi16newby](https://user-images.githubusercontent.com/3973243/63429007-d98e1900-c410-11e9-9128-900719a46343.png) | ![CiviContribute _ civi16newby (1)](https://user-images.githubusercontent.com/3973243/63435065-20ced680-c41e-11e9-9f69-936cb5123c44.png) | Yes |
| Manage Groups: paddings, gaps and the search form | ![Manage Groups _ civi16newby](https://user-images.githubusercontent.com/3973243/63434266-abaed180-c41c-11e9-8e05-95788a158572.png) | ![Manage Groups _ civi16newby …
=> SHOR-152: Fix misc issues

scss/civicrm/_variables.scss, scss/civicrm/common/_backgrounds.scss, scss/civicrm/common/_base.scss, scss/civicrm/common/_block-shadows.scss, scss/civicrm/common/_buttons.scss, scss/civicrm/common/_forms.scss, scss/civicrm/common/_modals.scss, scss/civicrm/common/_wizard.scss, scss/civicrm/contact/_collapse.scss, scss/civicrm/contact/_detail.scss, scss/civicrm/contact/pages/_contact-dedupefind.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_manage-groups.scss, scss/civicrm/contact/pages/_memberships.scss, scss/civicrm/contact/pages/_new-email.scss, scss/civicrm/contact/pages/_new-individual.scss, scss/civicrm/contact/pages/_new-price-set.scss, scss/civicrm/financial/_financial-batch.scss, scss/civicrm/mixins/_accordion.scss, scss/civicrm/mixins/_civicrm-table.scss, scss/civicrm/mixins/_input-text.scss, scss/civicrm/mixins/_panel-header.scss, scss/jquery/mixins/_ui-dialog.scss
This PR fixes miscellaneous issues with Shoreditch. Please see the **Changes** section below for more info.
| Mailing component - Accordion body padding | ![image](https://user-images.githubusercontent.com/3973243/63757952-e8624900-c8b2-11e9-9a0a-41c88701814d.png) | ![image](https://user-images.githubusercontent.com/3973243/63760564-78a28d00-c8b7-11e9-9c6a-ee361c559c94.png) | Yes |
| Dedupe exceptions - buttons are not styles | ![image](https://user-images.githubusercontent.com/3973243/63758059-1cd60500-c8b3-11e9-9a53-45be232f6818.png) |![image](https://user-images.githubusercontent.com/3973243/63760599-85bf7c00-c8b7-11e9-91b0-3b92204c483c.png) | Yes |
| New group modal with …
=> SHOR-152: Misc issues

scss/civicrm/common/_buttons.scss, scss/civicrm/common/_forms.scss, scss/civicrm/common/_main-menu.scss
This PR fixes KAM menu search and collapsible headers. Please see the Changes section for more info.
| KAM Search input | ![image](https://user-images.githubusercontent.com/3973243/63788581-a276a680-c8ed-11e9-9c41-843c16b799d1.png) ![image](https://user-images.githubusercontent.com/3973243/63788848-1a44d100-c8ee-11e9-95e4-2af729cf107c.png) | ![image](https://user-images.githubusercontent.com/3973243/63788001-aa821680-c8ec-11e9-8338-9d134021428c.png) ![image](https://user-images.githubusercontent.com/3973243/63788030-b53cab80-c8ec-11e9-99cd-58c9d4dc3d5c.png) | Yes |
| Collapsible headers | ![image](https://user-images.githubusercontent.com/3973243/63788519-8a068c00-c8ed-11e9-9b …
=> SHOR-152: Fix KAM menu search and collapsible headers

scss/civicrm/_variables.scss, scss/civicrm/administer/communication-organisation/_message-templates.scss, scss/civicrm/common/_buttons.scss, scss/civicrm/contact/_detail.scss, scss/civicrm/contact/_header.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/contact/pages/_events.scss, scss/civicrm/contact/pages/_new-email.scss, scss/civicrm/contact/pages/_relationships.scss, scss/civicrm/contact/pages/_tag-contacts.scss, scss/civicrm/mailing/pages/_mailing-report.scss, scss/civicrm/mixins/_table-selector.scss, scss/jquery/overrides/_select2.scss, scss/jquery/overrides/_tabs.scss
This PR fixes miscellaneous issues with Shoreditch. Please see the **Changes** section below for more info.
| What | Before  | After |
| ------------- | ------------- | ------------- |
| Contact add address (regression) | ![image](https://user-images.githubusercontent.com/3973243/63940978-82b4bf00-ca62-11e9-9836-2a1363af4b4e.png) | ![image](https://user-images.githubusercontent.com/3973243/63942511-ceb53300-ca65-11e9-805e-5c467557280b.png) |
| Contributions => Find contributions -> right click on view contribution and open in a new tab | ![View Contribution from Alexia Adams _ civi16newby](https://user-images.githubusercontent.com/3973243/63941059-b4c62100-ca62-11e9-8208-f4f2f7566ffb.png) | ![View Contribution from Alexia Adams _ civi16newby …
=> SHOR-151: Misc fixes

CRM/Shoreditch/Upgrader.php, README.md, shoreditch.php
We need to shoreditch theme to be enabled as a theme on installing the extension,  following the [theme system](https://docs.civicrm.org/dev/en/latest/framework/theme/) introduced on CiviCRM v5.16.
The theme has to be set by going to civicrm/admin/setting/preferences/display?reset=1
In hook_civicrm_install, "custom css url" is unset (if relevant) and 'theme_backend' setting is set to 'shoreditch'. This is done following the upgrader we already have in place [here](https://github.com/civicrm/org.civicrm.shoreditch/blob/d9953d0aee35ab6cf28a53d07ebcead3c427b7cc/CRM/Shoreditch/Upgrader.php#L13-L28).
=> SHOR-155: Enable Shoreditch As Backend Theme On Install

scss/civicrm/common/_jstree.scss
As a part of this PR the right click triggered menu is now appearing on administration navigation menu link.
The sub menu was JS behaviour was intact, it was just that it's z-index was not set to the correct value
Manual + BackstopJS.
=> SE-12: Fix edit menu opening issue on nav links

scss/civicrm/search/pages/_send-email.scss
This PR fixes the send email popup horizontal alignment and fix the horizontal scrollbar
Extra -ve margin was added to the email confirmation popup elements for contacts screen.
The changes are added in https://github.com/civicrm/org.civicrm.shoreditch/commit/751749cd0#diff-847cbd69e30c848777dc4ee29cdf1813R17-R22, which now seems stale and unnecessary and hence removing them.
Manual + BackstopJS.
=> SE-14: Fix email popup spacing issue

package-lock.json
This PR fixes all security vulnerabilities associated with shoreditch node modules
No visual changes introduced
Changes appeared after fixing node security vulnerabilities using `npm audit fix`
Manually testing each gulp task - everything seems to be working fine
=> SE-17: Fixes node modules vulnerabilities

gulpfile.js
This PR updates the branch name generated using `gulp release` command 
Currently, the branch name starts with `v` but this creates confusion while creating tags.
No visual changes introduced
This is done in order to follow the new release process and remove confusion.
=> SE-18: Fix the branch generation logic - remove 'v'

js/add-missing-date-addons.js, package.json
This PR removes an extra calendar icon that was being shown as a placeholder for calendar inputs.
It's important to know that the original calendar only has a placeholder and an input. The calendar button is added by a JS script that runs on start:
https://github.com/civicrm/org.civicrm.shoreditch/blob/master/js/add-missing-date-addons.js#L12
In order to remove the repeated calendar icon we remove the calendar icon:
```js
var placeholderWithoutCalendar = input.attr('placeholder').replace('', '');
```
The `` symbol is the font-awesome character used to display a calendar.
We use replace the icon with an empty string instead of replacing the whole placeholder attribute to avoid removing placeholder texts that the calendars might have. Current dates don't have placeholders apart from the …
=> SE-19: Remove calendar input placeholders

scss/civicrm/common/_modals.scss, scss/civicrm/contact/pages/_new-activity.scss
This PR fixes the spacing issue on assignee contact element on activity form and custom fields option value column alignment
This assignee field doesn't follow standard civicrm classes (another example of non standard HTML structure in core) and to fix this a patch was created in shoreditch in [Aug 2017 here](https://github.com/swastikpareek/org.civicrm.shoreditch/commit/751749cd0#diff-cba1f4ab8ef27ddb2acab0f0e81913bbR326). But since then shoreditch has evolved much and while writing new css fixes we might have forgot to update these patched css code and hence we had this issue.
Technically, this element had to have `view-value` class to match other ui styles on the page. since it didn't had this class so we have updated this selector with exact same styles than `view-value` class. So now …
=> SE-15: Fix misc issues on activity panel and activity pane popup

scss/civicrm/search/pages/_send-email.scss
This PR fixes the Send Email screen extra padding.
This is a regression issue, caused by https://github.com/civicrm/org.civicrm.shoreditch/pull/431.
The code removed in the above PR, fixed the margin issues when used inside an modal, but it also break the same page, when outside of modal.
To fix this, removed the following code
```scss
.crm-contactEmail-form-block {	
padding: 0 20px;	
}
```
There is no details available about why this code was specifically necesssary, so backstop tests were run to confirm that there are no regressions.
=> SE-24: Fix Email Screen Extra Padding

scss/civicrm/contact/pages/_manage-groups.scss
This PR fixes the broken header in Group Contacts screen.
In `_manage-groups.scss`, added
```scss
#{civi-page('group')} {
#searchForm {
...
width: auto !important;
}
}
```
Backstop tests were run, to ensure no regressions are present.
=> SE-25: Fix Group Contacts Header

scss/civicrm/_variables.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/mixins/_section-title.scss
This PR fixes the section titles width on the add contributions pages.
The section titles (`legend` inside `.CRM_Contribute_Form_Contribution` wrapper div) were given width of `100%` to forcefully render them as full bleed, but mixin `section-title` was also adding some padding to it which was making the _effective width to be 100px + 2 * horizontal-padding-unit_.
To fix this width was reduced by 2 * horizontal-padding-unit. Since the horizontal padding was not saved as a SASS variable. New SASS variables are documented in `_variables.scss` viz. `$crm-section-title-spacing-x` and `$crm-section-title-spacing-y`.
The variables are replaced at the place of spacing and width calculations.
Manual tests - Done
BackstopJS test - 5 Failed for contributions menu group
* Contributions - New …
=> BASW-641: Fix width of the section title on add contribution page

scss/civicrm/common/_base.scss
There was a bug with **More** menu item of actions menu on most pages - it was not visible (but was present on the page) so it was not possible to click it and select some action. Now its fixed.
To fix the issue we set `position: absolute` to the icon (`::after` element), which was missing and is required to make `right: -2px` work. Also `text-align: center` is added to improve icon alignment inside container.
I've ran backstop tests to verify changes implemented. Some tests failed, but all of them are either expected (because of implemented changes) or false alarms. So we can go ahead with this.
P.S. If you would want to run backstop tests again make sure to add `"misMatchThreshold": 0` to your `backstop.tpl.json` file, otherwise backstop would not notice this small change.
=> DRU-256: Fix actions menu icon visibility

package-lock.json, scss/bootstrap/overrides/crm/_button.scss, scss/civicrm/administer/civi-case/_case-types.scss, scss/civicrm/administer/common/_common.scss, scss/civicrm/administer/contribute/_managepremiums.scss, scss/civicrm/administer/display/_display.scss, scss/civicrm/common/_buttons.scss, scss/civicrm/contact/pages/_contributions.scss, scss/civicrm/financial/_batchtransaction.scss, scss/civicrm/search/pages/_advanced-search.scss, scss/civicrm/search/pages/_full-text-search.scss
Recently in the Civicrm Core(https://github.com/civicrm/civicrm-core/pull/18410), all the `input` type button markups has been changed to `button` elements. This caused a lot of styles to break when using Shoreditch theme. So this PR fixes those UI related style issues.
1. Changed css selector from `input` to `button` in
```
scss/civicrm/administer/contribute/_managepremiums.scss
scss/civicrm/common/_buttons.scss
scss/civicrm/contact/pages/_contributions.scss
scss/civicrm/financial/_batchtransaction.scss
scss/civicrm/search/pages/_full-text-search.scss
```
2. Made adjustments to the following files to support new markup
```
// There are no extra parent divs for buttons, so moved the css one level up
scss/bootstrap/overrides/crm/_button.scss 
// no extra css required for .crm-i, as items …
```
=> CPS-322: Support new Button markup

scss/bootstrap/overrides/crm/_button.scss, scss/civicrm/common/_buttons.scss
This PR fixes an issue where CiviCRM buttons inside of Bootstrap templates break.
All `.crm-button` and `.crm-form-submit` buttons inside of `#bootstrap-theme` would have their style overridden by a `color: inherit` https://github.com/civicrm/org.civicrm.shoreditch/commit/f3e73beeefa5cce3a1caf73e6a6166229749720d#diff-293f309d5b967b2ce90466201daefdeaad764020a635e624f1ac6b19d225fb2bR257 and `text-transform: none` https://github.com/civicrm/org.civicrm.shoreditch/commit/f3e73beeefa5cce3a1caf73e6a6166229749720d#diff-293f309d5b967b2ce90466201daefdeaad764020a635e624f1ac6b19d225fb2bR279 that should be applied to bootstrap buttons. To avoid this, we overrode the definitions for `.crm-button` and `.crm-form-submit` by adding an `!important` to their color and text transform properties. This way …
=> CPS-480: Fix broken buttons

scss/civicrm/common/_buttons.scss
In the latest CiviCRM update(5.35), there were new button classes were updated and hence introduced some UI impairments on the Direct Debit Batch pages. This PR fixes that.
* The action button on the Direct Debit wasn't using `crm-form-submit` class and hence the styles were broken. To fix this, we add `button.crm-form-xbutton` CSS selector to `button.crm-form-submit` CSS selector styles
* The `Go` button was having `.crm-button` class and hence the `float:left` property was getting applied to it. To fix this we reset the floats on the CRM buttons which just appear after the `.crm-form-select`
Link to the Github action workflow for running backstop tests - https://github.com/compucorp/backstopjs-config/actions/runs/657199439
- 9 scenarios failed - All are false alarms except `Search …
=> MAE-493: Style the form buttons and Direct Debit batch form actions

scss/civicrm/dashboard/_dashboard.scss, scss/civicrm/dashboard/dashlets/_activity-selector.scss, scss/civicrm/dashboard/dashlets/_reports.scss
Some of the dashlets inside the dashboard were in a broken state, this PR fixes that.
Report
Activities
Report
Activities
This is a regression of https://github.com/civicrm/org.civicrm.shoreditch/pull/495. 
All the existing styles were not moved to the new dashboard. Some of the styles were completely removed.
Backstop Report: As these styles only affect the Dashboard, only manual testing was done. As there is no chance of css leakage.
=> CPS-515: Fix Dashlet styles

scss/bootstrap/overrides/crm/_button.scss
The Cancel Button border was wrong when inside Bootstrap. This PR fixes it.
The button color was applied in https://github.com/civicrm/org.civicrm.shoreditch/commit/e948807afe6732c947a6a1b7456ecd59c09bad52#diff-d70c310903cd4caf4066146aa6a16294bb25f009a7f6a7f7b85d63c494525f3dR12. 
But there is no explanation of why this color was applied and `$gray-dark` is the correct color.
We never saw this before, because before CiviCRM 5.35 changes, there was an extra input element for buttons, and that input element had the correct colors.
Backstop Report: https://github.com/compucorp/backstopjs-config/actions/runs/675356335
=> CPS-481: Fix Button border

scss/bootstrap/overrides/crm/_button.scss
Similar to https://github.com/civicrm/org.civicrm.shoreditch/pull/492.
This PR removes the override made for `.crm-button-type-next` button.
CiviCase - https://github.com/compucorp/uk.co.compucorp.civicase/actions/runs/740312390
CiviCRM - https://github.com/compucorp/backstopjs-config/actions/runs/740130703
=> RSESPRT-33: Fix Next Button

scss/civicrm/contact/pages/_email-builder.scss
The preview button alignment was broken on the new mailing page for CiviCRM version 5.35.1. This PR fixes the button alignment on the New mailing page.
* Mailing preview button alignment was broken because CiviCRM 5.35.1 introduces extra `display` and `float` styles to `.crm-button` inside the `.civicrm-container`. See [this](https://github.com/civicrm/civicrm-core/blob/5.35.1/css/civicrm.css#L1893-L1894)
* To fix this we reset these values in the shoreditch custom overrides.
Backstop test run can be found at https://github.com/compucorp/backstopjs-config/actions/runs/701788475 
* Civicase - View case activity - False alarm
* Civicase - Case Time Spent Report - Grouping  - False alarm
* Find Contributions - Results - False alarm
* Find Contributions - Show Individual Payments - Results - …
=> MAE-511: Fix the alignment on new mailing page

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, scss/civicrm/administer/contribute/_contribute.scss, scss/civicrm/administer/customize-data/_customize-data.scss, scss/civicrm/administer/system-status/_configtask.scss, scss/civicrm/cases/_dashboard.scss, scss/civicrm/common/_tables.scss, scss/civicrm/contact/pages/_events.scss, scss/civicrm/contact/pages/_reports.scss
When the Case Status had a Dark Colored background in the Option Settings, the Case Status label were shown as white text on white background, this PR fixes that problem.
The Background Color of Case Status label should ideally be same as the color set in Option Settings.
But in `scss/civicrm/common/_tables.scss`, the Background was forced to Color White using `!important`, and that ignored the inline background color styles.
Now `!important` is removed, and individual styles are tables to tables where this White Background needs to be forced.
Backstop Tests are done in https://github.com/compucorp/backstopjs-config/actions/runs/700673399
=> CPS-378: Fix Case Status labels

scss/civicrm/common/_accordions.scss
Fixed the `helpicon` font color when inside a CRM Accordion Header element.
In https://github.com/civicrm/org.civicrm.shoreditch/pull/35/files#diff-80b1b289804999801a1c94d7aa7c41802b4047cded601b06fd2846ff1c75614eR46, the font color was set to `$brand-primary;`, but it was clearly wrong. Because in Blue Background, blue font wont be visible. So changed it to white.
Backstop Tests - https://github.com/compucorp/backstopjs-config/actions/runs/743927816
=> RSE-1609: Fix help icon

scss/civicrm/custom-civicrm.scss
Shoreditch uses FontAwesome v4. But if Drupal loads Font Awesome v5, then all the icons in CiviCRM does not work anymore. This PR fixes the same.
FontAwesome v4 works fine when used inside `$bootstrap-theme`, because of https://github.com/civicrm/org.civicrm.shoreditch/blob/a3c253a0ec40e7aae78e93d90a6915270d5a9a4e/scss/bootstrap/bootstrap.scss#L2. As it embeds the whole FontAwesome v4 inside `$bootstrap-theme` namespace.
But the same was not true when used outside of `$bootstrap-theme`. Because in https://github.com/civicrm/org.civicrm.shoreditch/blob/c9c7bb646a726a461676011d2c9a41cffd6208a9/scss/civicrm/custom-civicrm.scss#L9-L10, only the Variables and Paths were added.
Now added `@import 'bootstrap/vendor/font-awesome/font-awesome';` inside `scss/civicrm/custom-civicrm.scss`, so that …
=> ACUSPRT-81: Add FontAwesome inside custom-civicrm.scss

.github/PULL_REQUEST_TEMPLATE.md, scss/civicrm/contact/pages/_export.scss
This PR fixes the style of the form for saving a set of fields after a contact export action.
On the `Export Options` tab, choosing "Select fields for export":
We are moved to select the required fields. Then, the dialog presented there has the "Save fields " button disabled and almost no visible:
even after entering text on the input:
The button on the dialog window is visible, presenting an appropriate disabled style:
After entering text on the input, the disabled style is removed:
And also, a hover effect was added:
Backstop Tests: https://github.com/compucorp/backstopjs-config/actions/runs/906013759
=> RSE-1608: Adjust style for export dialog

scss/civicrm/contact/_detail.scss
In the contact summary page, if the Name of the Location Type is too long and it is without any Spaces, it breaks the UI. This PR fixes the same.
Added `word-break: break-all;` to fix this issue.
Also Ignore Linter rules are added for the `scss/civicrm/contact/_detail.scss` file. As this file overrides core styles, it is necessary to ignore these rules.
https://github.com/compucorp/backstopjs-config/actions/runs/1029463378
=> ASESPRT-405: Break long "Location Type" name strings

js/add-missing-date-addons.js
Get this error on extended reports in combination with shoreditch
```
11:28:42.212 add-missing-date-addons.js?qnvpbs:15 Uncaught TypeError: Cannot read property 'replace' of undefined
at addDateAddonToInput (add-missing-date-addons.js?qnvpbs:15)
at HTMLInputElement.<anonymous> (add-missing-date-addons.js?qnvpbs:50)
at Function.each (jquery.js?qnvpbs:371)
at jQuery.fn.init.each (jquery.js?qnvpbs:137)
at MutationObserver.<anonymous> (add-missing-date-addons.js?qnvpbs:46)
at add-missing-date-addons.js?qnvpbs:69
addDateAddonToInput @ add-missing-date-addons.js?qnvpbs:15
(anonymous) @ add-missing-date-addons.js?qnvpbs:50
each @ jquery.js?qnvpbs:371
each @ jquery.js?qnvpbs:137
(anonymous) @ add-missing-date-addons.js?qnvpbs:46
(anonymous) @ add-missing-date-addons.js?qnvpbs:69
setTimeout …
```
=> fix console error for extended reports

scss/civicrm/mixins/_expandable-table.scss
There was an issue with expand/collapse icons - 2 icons overlapped each other, this issue appeared in any expandable tables. Now it's fixed.
Here we had an interesting collision: icon from shoreditch theme set to `::after` element was overlaped by icon coming from native civicrm styles set to `::before` element.
First I was thinking to refactor shoreditch - move icon to `::before` element, but maybe `::after` element is used for a reason, as I don't have background here, I decided to keep the icon in `::after`.
Then I've tried couple of options of hiding `::before` element (civicrm icon): first I've set `display: none`, but got this:
This element has `width: 1em` which acts like a margin between icon and text.
Setting `font-size: 0` causing similar issue.
So if we decided to keep this …
=> MAE-369: Fix expand/collapse icons overlap

scss/civicrm/contact/_detail.scss
Long labels might sometimes be cut mid-word, which looks a bit odd.
`break-word` instead of `break-all`
=> Labels: break-word instead of break-all, to avoid cutting a word

shoreditch.php
This PR solves the theme problem that appears after clearing the DB Cache
The problem observed consists of the Shoreditch theme not loading correctly at some intervals, but that situation gets solved after refreshing the page. This is an example of how the interface looks:
The error can be reproduced by executing the Job that clears the DB Cache:
**Note** The job usually runs by a console, not using the "Execute now" in the UI as I did on the demo, then the page refresh that we are seeing is not performed. This causes that the next user to access the site after the cron runs in the background sees the error on the theme.
The error after clearing DB Cache does not appear anymore:
The function `_shoreditch_isActive` depends on [Civi::service('themes')->getActiveThemeKey()](https://github.com …
=> MAE-633: Regenerate CiviCRM menu if it is empty

info.xml
* MAE-633: Regenerate CiviCRM menu if it is empty #535
No changes on the CSS were added to this release.
https://github.com/compucorp/backstopjs-config/actions/runs/1991524616
=> COMCL-188: Release v1.0.0-beta.11

scss/civicrm/common/_main-menu.scss
This PR fixes the issue with missing spacing in the quick search result dropdown, this issue is caused by a change in the dropdown item CSS class in the recent CiviCRM version.
The CSS class used to be `ui-menu-item-wrapper` but now `ui-menu-item-uiMenuItemWrapper`, added support for the two classes to ensure backward compatibility.
On an older version of CiviCRM, 5.35.2
On a newer version of CiviCRM, 5.39.1
On a newer version of CiviCRM, 5.39.1
[Backstop JS report here](https://github.com/compucorp/backstopjs-config/actions/runs/2717988065)
=> CATL-2243: Fix quick search result dropdown

info.xml, mixin/menu-xml@1.0.0.mixin.php, mixin/polyfill.php, mixin/setting-php@1.0.0.mixin.php, mixin/theme-php@1.0.0.mixin.php, shoreditch.civix.php, shoreditch.php
Extension is outdated and throw error in PHP 7.4
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated
No errors
Rebuild civix with built in function civix generate:module
=> Rebuild civix for PHP 7.4 support

scss/civicrm/common/_buttons.scss
This PR aligns the button with their help icon on the contacts group page.
Behaviour in the latest CiviCRM (tested with 5.51.3) with Shoreditch, the help icons are away from the buttons.
The default behaviour in CiviCRM without Shoreditch.
Behaviour in the latest CiviCRM (tested with 5.51.3) with Shoreditch.
In this https://github.com/civicrm/civicrm-core/commit/044fc18f4a8afdcfd2ef1a552d05be09a6f3b1b6 included in CiviCRM [5.42.0](https://github.com/civicrm/civicrm-core/releases/tag/5.42.0), buttons in the contacts group page were added to a single div group and a CSS rule to float the icon was added, this is causing an issue in Shoreditch theme forcing the helo icons to float away from their respective buttons.
We simply set the float to none, for the help icons to be rightly placed …
=> MAE-965: Align button with help icon on contacts group page

scss/bootstrap/overrides/_variables.scss, scss/bootstrap/overrides/style/_pagination.scss, scss/civicrm/_variables.scss, scss/civicrm/common/_common.scss, scss/civicrm/common/_search-display-pager.scss, scss/civicrm/common/_tables.scss
This PR updates search kit tables and default table styles.
We try to tweak the styles to make the search kit tables match the theme styles (mainly the padding and the pager to be similar to other tables). Please note, the search kit uses the [table-striped](https://getbootstrap.com/docs/3.3/css/#tables-striped) to add the striped effect.
Also, updated the default table styles to match other CiviCRM core tables.
=> CIWEMB-376: Update table styles

scss/civicrm/common/_block-shadows.scss
Previously, when an error or alert occurred, the toast message would be obscured by the modal, potentially causing users to miss it and preventing them from dismissing it. 
The alert box was positioned behind the modal overlay, making it less visible and inaccessible for dismissal by the user.
Now, the alert box appears above the modal overlay and can be dismissed by the user.
=> PROD-190: Ensure alert is visible when modal is displayed
